class AppConstants {
  List<String> appZipCodeList = [
    "75001, TX, USA",
    "75002, TX, USA",
    "75006, TX, USA",
    "75007, TX, USA",
    "75009, TX, USA",
    "75010, TX, USA",
    "75019, TX, USA",
    "75023, TX, USA",
    "75028, TX, USA",
    "75032, TX, USA",
    "75033, TX, USA",
    "75034, TX, USA",
    "75035, TX, USA",
    "75038, TX, USA",
    "75039, TX, USA",
    "75040, TX, USA",
    "75041, TX, USA",
    "75042, TX, USA",
    "75043, TX, USA",
    "75048, TX, USA",
    "75050, TX, USA",
    "75051, TX, USA",
    "75052, TX, USA",
    "75056, TX, USA",
    "75057, TX, USA",
    "75060, TX, USA",
    "75061, TX, USA",
    "75062, TX, USA",
    "75063, TX, USA",
    "75065, TX, USA",
    "75067, TX, USA",
    "75068, TX, USA",
    "75069, TX, USA",
    "75070, TX, USA",
    "75071, TX, USA",
    "75074, TX, USA",
    "75075, TX, USA",
    "75077, TX, USA",
    "75078, TX, USA",
    "75080, TX, USA",
    "75081, TX, USA",
    "75082, TX, USA",
    "75083, TX, USA",
    "75085, TX, USA",
    "75087, TX, USA",
    "75088, TX, USA",
    "75090, TX, USA",
    "75093, TX, USA",
    "75094, TX, USA",
    "75098, TX, USA",
    "75104, TX, USA",
    "75116, TX, USA",
    "75126, TX, USA",
    "75132, TX, USA",
    "75134, TX, USA",
    "75135, TX, USA",
    "75141, TX, USA",
    "75142, TX, USA",
    "75149, TX, USA",
    "75150, TX, USA",
    "75154, TX, USA",
    "75159, TX, USA",
    "75160, TX, USA",
    "75164, TX, USA",
    "75165, TX, USA",
    "75166, TX, USA",
    "75172, TX, USA",
    "75173, TX, USA",
    "75180, TX, USA",
    "75182, TX, USA",
    "75201, TX, USA",
    "75202, TX, USA",
    "75203, TX, USA",
    "75205, TX, USA",
    "75211, TX, USA",
    "75215, TX, USA",
    "75216, TX, USA",
    "75217, TX, USA",
    "75225, TX, USA",
    "75230, TX, USA",
    "75234, TX, USA",
    "75240, TX, USA",
    "75401, TX, USA",
    "75407, TX, USA",
    "75409, TX, USA",
    "75428, TX, USA",
    "75442, TX, USA",
    "76001, TX, USA",
    "76002, TX, USA",
    "76006, TX, USA",
    "76008, TX, USA",
    "76009, TX, USA",
    "76010, TX, USA",
    "76012, TX, USA",
    "76016, TX, USA",
    "76018, TX, USA",
    "76020, TX, USA",
    "76021, TX, USA",
    "76022, TX, USA",
    "76034, TX, USA",
    "76036, TX, USA",
    "76039, TX, USA",
    "76040, TX, USA",
    "76050, TX, USA",
    "76051, TX, USA",
    "76052, TX, USA",
    "76053, TX, USA",
    "76058, TX, USA",
    "76060, TX, USA",
    "76063, TX, USA",
    "76065, TX, USA",
    "76084, TX, USA",
    "76086, TX, USA",
    "76087, TX, USA",
    "76092, TX, USA",
    "76102, TX, USA",
    "76103, TX, USA",
    "76104, TX, USA",
    "76105, TX, USA",
    "76107, TX, USA",
    "76108, TX, USA",
    "76109, TX, USA",
    "76110, TX, USA",
    "76112, TX, USA",
    "76114, TX, USA",
    "76116, TX, USA",
    "76117, TX, USA",
    "76118, TX, USA",
    "76119, TX, USA",
    "76123, TX, USA",
    "76126, TX, USA",
    "76131, TX, USA",
    "76134, TX, USA",
    "76137, TX, USA",
    "76140, TX, USA",
    "76148, TX, USA",
    "76177, TX, USA",
    "76179, TX, USA",
    "76180, TX, USA",
    "76182, TX, USA",
    "76201, TX, USA",
    "76205, TX, USA",
    "76207, TX, USA",
    "76208, TX, USA",
    "76209, TX, USA",
    "76210, TX, USA",
    "76226, TX, USA",
    "76227, TX, USA",
    "76247, TX, USA",
    "76248, TX, USA",
    "76249, TX, USA",
    "76258, TX, USA",
    "76259, TX, USA",
    "76262, TX, USA",
    "78701, TX, USA",
    "78702, TX, USA",
    "78703, TX, USA",
    "78704, TX, USA",
    "78705, TX, USA",
    "78712, TX, USA",
    "78721, TX, USA",
    "78722, TX, USA",
    "78723, TX, USA",
    "78724, TX, USA",
    "78725, TX, USA",
    "78726, TX, USA",
    "78727, TX, USA",
    "78728, TX, USA",
    "78729, TX, USA",
    "78730, TX, USA",
    "78731, TX, USA",
    "78732, TX, USA",
    "78733, TX, USA",
    "78734, TX, USA",
    "78735, TX, USA",
    "78736, TX, USA",
    "78737, TX, USA",
    "78738, TX, USA",
    "78739, TX, USA",
    "78741, TX, USA",
    "78742, TX, USA",
    "78744, TX, USA",
    "78745, TX, USA",
    "78746, TX, USA",
    "78747, TX, USA",
    "78748, TX, USA",
    "78749, TX, USA",
    "78750, TX, USA",
    "78751, TX, USA",
    "78752, TX, USA",
    "78753, TX, USA",
    "78754, TX, USA",
    "78756, TX, USA",
    "78757, TX, USA",
    "78758, TX, USA",
    "78759, TX, USA",
    "78760, TX, USA",
    "78761, TX, USA",
    "78762, TX, USA",
    "78763, TX, USA",
    "78764, TX, USA",
    "78765, TX, USA",
    "78766, TX, USA",
    "78767, TX, USA",
    "78768, TX, USA",
    "78769, TX, USA",
    "78772, TX, USA",
    "78773, TX, USA",
    "78774, TX, USA",
    "78778, TX, USA",
    "78779, TX, USA",
    "78780, TX, USA",
    "78781, TX, USA",
    "78783, TX, USA",
    "78785, TX, USA",
    "78789, TX, USA",
  ];
  List<String> appCitiesList = [
    "Dallas, TX, USA",
    "Fort Worth, TX, USA",
    "Arlington, TX, USA",
    "Plano, TX, USA",
    "Irving, TX, USA",
    "Garland, TX, USA",
    "Denton, TX, USA",
    "Richardson, TX, USA",
    "Frisco, TX, USA",
    "McKinney, TX, USA",
    "Grand Prairie, TX, USA",
    "Lewisville, TX, USA",
    "Grapevine, TX, USA",
    "Carrollton, TX, USA",
    "Mesquite, TX, USA",
    "Allen, TX, USA",
    "Flower Mound, TX, USA",
    "Euless, TX, USA",
    "Bedford, TX, USA",
    "Coppell, TX, USA",
    "Southlake, TX, USA",
    "North Richland Hills, TX, USA",
    "Mansfield, TX, USA",
    "Rowlett, TX, USA",
    "Wylie, TX, USA",
    "Keller, TX, USA",
    "Addison, TX, USA",
    "Aledo, TX, USA",
    "Alma, TX, USA",
    "Alvarado, TX, USA",
    "Alvord, TX, USA",
    "Angus, TX, USA",
    "Anna, TX, USA",
    "Annetta, TX, USA",
    "Annetta North, TX, USA",
    "Annetta South, TX, USA",
    "Archer City, TX, USA",
    "Argyle, TX, USA",
    "Aubrey, TX, USA",
    "Aurora, TX, USA",
    "Azle, TX, USA",
    "Bailey, TX, USA",
    "Balch Springs, TX, USA",
    "Bardwell, TX, USA",
    "Barry, TX, USA",
    "Bartonville, TX, USA",
    "Bellevue, TX, USA",
    "Bells, TX, USA",
    "Benbrook, TX, USA",
    "Blooming Grove, TX, USA",
    "Blue Mound, TX, USA",
    "Blue Ridge, TX, USA",
    "Bonham, TX, USA",
    "Bowie, TX, USA",
    "Boyd, TX, USA",
    "Brazos Bend, TX, USA",
    "Breckenridge, TX, USA",
    "Briaroaks, TX, USA",
    "Bridgeport, TX, USA",
    "Bryson, TX, USA",
    "Burkburnett, TX, USA",
    "Burleson, TX, USA",
    "Byers, TX, USA",
    "Caddo Mills, TX, USA",
    "Callisburg, TX, USA",
    "Campbell, TX, USA",
    "Cashion Community, TX, USA",
    "Cedar Hill, TX, USA",
    "Celeste, TX, USA",
    "Celina, TX, USA",
    "Chico, TX, USA",
    "Chillicothe, TX, USA",
    "Cleburne, TX, USA",
    "Cockrell Hill, TX, USA",
    "Colleyville, TX, USA",
    "Collinsville, TX, USA",
    "Commerce, TX, USA",
    "Cool, TX, USA",
    "Copper Canyon, TX, USA",
    "Combine, TX, USA",
    "Corinth, TX, USA",
    "Corral City, TX, USA",
    "Corsicana, TX, USA",
    "Cottonwood, TX, USA",
    "Coyote Flats, TX, USA",
    "Crandall, TX, USA",
    "Cresson, TX, USA",
    "Cross Roads, TX, USA",
    "Cross Timber, TX, USA",
    "Crowell, TX, USA",
    "Crowley, TX, USA",
    "Dalworthington Gardens, TX, USA",
    "Dawson, TX, USA",
    "Decatur, TX, USA",
    "Dean, TX, USA",
    "DeCordova, TX, USA",
    "Denison, TX, USA",
    "DeSoto, TX, USA",
    "Dish, TX, USA",
    "Dodd City, TX, USA",
    "Dorchester, TX, USA",
    "Double Oak, TX, USA",
    "Dublin, TX, USA",
    "Duncanville, TX, USA",
    "Eagle Mountain, TX, USA",
    "Ector, TX, USA",
    "Edgecliff Village, TX, USA",
    "Elizabethtown, TX, USA",
    "Emhouse, TX, USA",
    "Ennis, TX, USA",
    "Eureka, TX, USA",
    "Everman, TX, USA",
    "Fairview, TX, USA",
    "Farmers Branch, TX, USA",
    "Farmersville, TX, USA",
    "Fate, TX, USA",
    "Ferris, TX, USA",
    "Forest Hill, TX, USA",
    "Forney, TX, USA",
    "Frost, TX, USA",
    "Gainesville, TX, USA",
    "Garrett, TX, USA",
    "Glen Rose, TX, USA",
    "Glenn Heights, TX, USA",
    "Godley, TX, USA",
    "Goodlow, TX, USA",
    "Gordon, TX, USA",
    "Graford, TX, USA",
    "Graham, TX, USA",
    "Granbury, TX, USA",
    "Grandview, TX, USA",
    "Greenville, TX, USA",
    "Gunter, TX, USA",
    "Hackberry, TX, USA",
    "Haltom City, TX, USA",
    "Haslet, TX, USA",
    "Hawk Cove, TX, USA",
    "Heath, TX, USA",
    "Hebron, TX, USA",
    "Henrietta, TX, USA",
    "Hickory Creek, TX, USA",
    "Highland Park, TX, USA",
    "Highland Village, TX, USA",
    "Holliday, TX, USA",
    "Honey Grove, TX, USA",
    "Howe, TX, USA",
    "Hudson Oaks, TX, USA",
    "Hurst, TX, USA",
    "Hutchins, TX, USA",
    "Iowa Park, TX, USA",
    "Italy, TX, USA",
    "Jacksboro, TX, USA",
    "Jolly, TX, USA",
    "Josephine, TX, USA",
    "Joshua, TX, USA",
    "Justin, TX, USA",
    "Kaufman, TX, USA",
    "Keene, TX, USA",
    "Kemp, TX, USA",
    "Kennedale, TX, USA",
    "Kerens, TX, USA",
    "Knollwood, TX, USA",
    "Krugerville, TX, USA",
    "Ladonia, TX, USA",
    "Lancaster, TX, USA",
    "Lake Bridgeport, TX, USA",
    "Lake Dallas, TX, USA",
    "Lake Worth, TX, USA",
    "Lakeside, TX, USA",
    "Lakeside City, TX, USA",
    "Lakewood Village, TX, USA",
    "Lavon, TX, USA",
    "Leonard, TX, USA",
    "Lincoln Park, TX, USA",
    "Lindsay, TX, USA",
    "Lipan, TX, USA",
    "Little Elm, TX, USA",
    "Lone Oak, TX, USA",
    "Lowry Crossing, TX, USA",
    "Lucas, TX, USA",
    "Mabank, TX, USA",
    "Maypearl, TX, USA",
    "Megargel, TX, USA",
    "McLendon-Chisholm, TX, USA",
    "Melissa, TX, USA",
    "Meridian, TX, USA",
    "Midlothian, TX, USA",
    "Mildred, TX, USA",
    "Millsap, TX, USA",
    "Mineral Wells, TX, USA",
    "Mingus, TX, USA",
    "Mobile City, TX, USA",
    "Muenster, TX, USA",
    "Murphy, TX, USA",
    "Mustang, TX, USA",
    "Navarro, TX, USA",
    "Nevada, TX, USA",
    "New Fairview, TX, USA",
    "New Hope, TX, USA",
    "Newark, TX, USA",
    "Newcastle, TX, USA",
    "Neylandville, TX, USA",
    "Nocona, TX, USA",
    "Northlake, TX, USA",
    "North Richland H, TX, USAills",
    "Oak Grove, TX, USA",
    "Oak Leaf, TX, USA",
    "Oak Point, TX, USA",
    "Oak Ridge (Cooke County), TX, USA",
    "Oak Ridge (Kaufman County), TX, USA",
    "Oak Valley, TX, USA",
    "Olney, TX, USA",
    "Ovilla, TX, USA",
    "Paducah, TX, USA",
    "Palmer, TX, USA",
    "Pantego, TX, USA",
    "Paradise, TX, USA",
    "Parker, TX, USA",
    "Pecan Hill, TX, USA",
    "Pelican Bay, TX, USA",
    "Petrolia, TX, USA",
    "Pilot Point, TX, USA",
    "Pleasant Valley, TX, USA",
    "Ponder, TX, USA",
    "Post Oak Bend City, TX, USA",
    "Pottsboro, TX, USA",
    "Powell, TX, USA",
    "Princeton, TX, USA",
    "Prosper, TX, USA",
    "Providence Village, TX, USA",
    "Quanah, TX, USA",
    "Quinlan, TX, USA",
    "Ravenna, TX, USA",
    "Red Oak, TX, USA",
    "Retreat, TX, USA",
    "Rhome, TX, USA",
    "Reno, TX, USA",
    "Rice, TX, USA",
    "Richland, TX, USA",
    "Richland Hills, TX, USA",
    "Rio Vista, TX, USA",
    "River Oaks, TX, USA",
    "Roanoke, TX, USA",
    "Rockwall, TX, USA",
    "Royse City, TX, USA",
    "Runaway Bay, TX, USA",
    "Sachse, TX, USA",
    "Sadler, TX, USA",
    "Saginaw, TX, USA",
    "Sanctuary, TX, USA",
    "Sanger, TX, USA",
    "Sansom Park, TX, USA",
    "Savoy, TX, USA",
    "Seagoville, TX, USA",
    "Scotland, TX, USA",
    "Scurry, TX, USA",
    "Seymour, TX, USA",
    "Shady Shores, TX, USA",
    "Sherman, TX, USA",
    "Southmayd, TX, USA",
    "Springtown, TX, USA",
    "St. Jo, TX, USA",
    "St. Paul, TX, USA",
    "Stephenville, TX, USA",
    "Strawn, TX, USA",
    "Sunnyvale, TX, USA",
    "Talty, TX, USA",
    "Terrell, TX, USA",
    "The Colony, TX, USA",
    "Tioga, TX, USA",
    "Tolar, TX, USA",
    "Tom Bean, TX, USA",
    "Trenton, TX, USA",
    "Trophy Club, TX, USA",
    "Union Valley, TX, USA",
    "University Park, TX, USA",
    "Valley View, TX, USA",
    "Van Alstyne, TX, USA",
    "Venus, TX, USA",
    "Vernon, TX, USA",
    "Waxahachie, TX, USA",
    "Watauga, TX, USA",
    "Weatherford, TX, USA",
    "West Tawakoni, TX, USA",
    "Westlake, TX, USA",
    "Westover Hills, TX, USA",
    "Westworth Village, TX, USA",
    "Whitesboro, TX, USA",
    "White Settlement, TX, USA",
    "Whitewright, TX, USA",
    "Wilmer, TX, USA",
    "Windom, TX, USA",
    "Windthorst, TX, USA",
    "Wolfe City, TX, USA",
    "Houston, TX, USA",
    "San Antonio, TX, USA",
    "Austin, TX, USA",
    "El Paso, TX, USA",
    "Corpus Christi, TX, USA",
    "Laredo, TX, USA",
    "Lubbock, TX, USA",
    "Amarillo, TX, USA",
    "Brownsville, TX, USA",
    "Pasadena, TX, USA",
    "Killeen, TX, USA",
    "McAllen, TX, USA",
    "Midland, TX, USA",
    "Waco, TX, USA",
    "Round Rock, TX, USA",
    "Abilene, TX, USA",
    "Pearland, TX, USA",
    "Richardson, TX, USA",
    "Round Rock, TX, USA",
    "Cedar Park, TX, USA",
    "Georgetown, TX, USA",
    "Pflugerville, TX, USA",
    "Leander, TX, USA",
    "Bee Cave, TX, USA",
    "Lakeway, TX, USA",
    "Kyle, TX, USA",
    "Buda, TX, USA",
    "Dripping Springs, TX, USA",
    "West Lake Hills, TX, USA",
    "San Marcos, TX, USA",
    "Manor, TX, USA",
    "Hutto, TX, USA",
    "Liberty Hill, TX, USA",
    "Elgin, TX, USA",
    "Bastrop, TX, USA",
    "Lago Vista, TX, USA",
    "Jonestown, TX, USA",
    "Taylor, TX, USA",
    "Spicewood, TX, USA",
    "Wimberley, TX, USA",
    "Sunset Valley, TX, USA",
    "Rollingwood, TX, USA",
    "Del Valle, TX, USA",
    "Smithville, TX, USA",
    "Burnet, TX, USA",
    "Marble Falls, TX, USA",
    "Lockhart, TX, USA",
    "New Braunfels, TX, USA",
    "Seguin, TX, USA",
    "Canyon Lake, TX, USA",
    "Bastrope, TX, USA",
    "Shady Hollow, TX, USA",
    "Wells Branch, TX, USA",
    "Lost Creek, TX, USA",
    "Bee Creek, TX, USA",
    "Briarcliff, TX, USA",
    "Creedmoor, TX, USA",
    "Mustang Ridge, TX, USA",
    "Niederwald, TX, USA",
    "Uhland, TX, USA",
    "Webberville, TX, USA",
    "Windemere, TX, USA",
    "Jarrell, TX, USA",
    "Bertram, TX, USA",
    "Volente, TX, USA",
    "Driftwood, TX, USA",
    "Manchaca (now officially named Menchaca), TX, USA",
    "Mountain City, TX, USA",
    "Point Venture, TX, USA",
    "The Hills, TX, USA",
    "Serenada, TX, USA",
    "Thorndale, TX, USA",
    "Thrall, TX, USA",
    "Granger, TX, USA",
    "Coupland, TX, USA",
    "McDade, TX, USA",
    "Paige, TX, USA",
    "Red Rock, TX, USA",
    "Dale, TX, USA",
    "Fischer, TX, USA",
    "Johnson City, TX, USA",
    "Blanco, TX, USA",
    "Cedar Creek, TX, USA",
    "Martindale, TX, USA",
    "Maxwell, TX, USA",
    "Staples, TX, USA",
  ];
}
